name = "dontuknowpe-api"
main = "src/index.ts"
compatibility_date = "2024-06-20"

# Bindings (fill IDs after creating resources)
kv_namespaces = []

d1_databases = [
	# Local-only DB for dev; wrangler uses .wrangler/state for the path
	{ binding = "DB", database_name = "dontuknowpe_db", database_id = "local", migrations_dir = "migrations" }
]

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

[env.production]
vars = { }
kv_namespaces = []
d1_databases = [
	# Fill with real DB: wrangler d1 create dontuknowpe-db
	# Set database_id below to your production D1 UUID via CI before deploy
	{ binding = "DB", database_name = "dontuknowpe-db", database_id = "<id>", migrations_dir = "migrations" }
]
