name = "dontuknowpe-api"
main = "src/index.ts"
compatibility_date = "2024-06-20"

# Bindings (fill IDs after creating resources)
# kv_namespaces = [
#   { binding = "KV_CONFIG", id = "<your-kv-id>" }
# ]

# d1_databases = [
#   { binding = "DB", database_name = "dontuknowpe-db", database_id = "<your-d1-id>" }
# ]

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]
