name: Deploy Azure Functions API

on:
  push:
    branches: [ main ]
    paths:
      - 'api-azure/**'
      - '.github/workflows/api-azure-deploy.yml'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-azure
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: api-azure

      # Optional: set app settings via CLI if you keep them in GitHub Secrets
      # - name: Configure App Settings
      #   uses: azure/CLI@v2
      #   with:
      #     inlineScript: |
      #       az functionapp config appsettings set \
      #         --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
      #         --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
      #         --settings \
      #           WebPubSubConnectionString=${{ secrets.WEBPUBSUB_CONNECTION_STRING }} \
      #           WEBPUBSUB_HUB=rooms \
      #           RedisConnectionString=${{ secrets.REDIS_CONNECTION_STRING }} \
      #           ADMIN_START_SECRET=${{ secrets.ADMIN_START_SECRET }}
